/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideInternationalRelationsJobsRequirementsRouteImport } from './routes/guide.international-relations-jobs-requirements'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CoachesApplyRouteImport } from './routes/coaches.apply'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedResumeReviewIndexRouteImport } from './routes/_authenticated/resume-review.index'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer.index'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedResumeReviewReturnRouteImport } from './routes/_authenticated/resume-review.return'
import { Route as AuthenticatedResumeReviewCheckoutRouteImport } from './routes/_authenticated/resume-review.checkout'
import { Route as AuthenticatedMembershipReturnRouteImport } from './routes/_authenticated/membership.return'
import { Route as AuthenticatedMembershipCheckoutRouteImport } from './routes/_authenticated/membership.checkout'
import { Route as AuthenticatedEmployerResumesRouteImport } from './routes/_authenticated/employer.resumes'
import { Route as AuthenticatedCoachClientsRouteImport } from './routes/_authenticated/coach.clients'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideInternationalRelationsJobsRequirementsRoute =
  GuideInternationalRelationsJobsRequirementsRouteImport.update({
    id: '/guide/international-relations-jobs-requirements',
    path: '/guide/international-relations-jobs-requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesApplyRoute = CoachesApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CoachesRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeReviewIndexRoute =
  AuthenticatedResumeReviewIndexRouteImport.update({
    id: '/resume-review/',
    path: '/resume-review/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumeReviewReturnRoute =
  AuthenticatedResumeReviewReturnRouteImport.update({
    id: '/resume-review/return',
    path: '/resume-review/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeReviewCheckoutRoute =
  AuthenticatedResumeReviewCheckoutRouteImport.update({
    id: '/resume-review/checkout',
    path: '/resume-review/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembershipReturnRoute =
  AuthenticatedMembershipReturnRouteImport.update({
    id: '/membership/return',
    path: '/membership/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembershipCheckoutRoute =
  AuthenticatedMembershipCheckoutRouteImport.update({
    id: '/membership/checkout',
    path: '/membership/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerResumesRoute =
  AuthenticatedEmployerResumesRouteImport.update({
    id: '/resumes',
    path: '/resumes',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedCoachClientsRoute =
  AuthenticatedCoachClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/employers': typeof EmployersRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/coaches/apply': typeof CoachesApplyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guide/international-relations-jobs-requirements': typeof GuideInternationalRelationsJobsRequirementsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coach/clients': typeof AuthenticatedCoachClientsRoute
  '/employer/resumes': typeof AuthenticatedEmployerResumesRoute
  '/membership/checkout': typeof AuthenticatedMembershipCheckoutRoute
  '/membership/return': typeof AuthenticatedMembershipReturnRoute
  '/resume-review/checkout': typeof AuthenticatedResumeReviewCheckoutRoute
  '/resume-review/return': typeof AuthenticatedResumeReviewReturnRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/resume-review/': typeof AuthenticatedResumeReviewIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/employers': typeof EmployersRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/coaches/apply': typeof CoachesApplyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guide/international-relations-jobs-requirements': typeof GuideInternationalRelationsJobsRequirementsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coach/clients': typeof AuthenticatedCoachClientsRoute
  '/employer/resumes': typeof AuthenticatedEmployerResumesRoute
  '/membership/checkout': typeof AuthenticatedMembershipCheckoutRoute
  '/membership/return': typeof AuthenticatedMembershipReturnRoute
  '/resume-review/checkout': typeof AuthenticatedResumeReviewCheckoutRoute
  '/resume-review/return': typeof AuthenticatedResumeReviewReturnRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/resume-review': typeof AuthenticatedResumeReviewIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/employers': typeof EmployersRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/coaches/apply': typeof CoachesApplyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guide/international-relations-jobs-requirements': typeof GuideInternationalRelationsJobsRequirementsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/coach/clients': typeof AuthenticatedCoachClientsRoute
  '/_authenticated/employer/resumes': typeof AuthenticatedEmployerResumesRoute
  '/_authenticated/membership/checkout': typeof AuthenticatedMembershipCheckoutRoute
  '/_authenticated/membership/return': typeof AuthenticatedMembershipReturnRoute
  '/_authenticated/resume-review/checkout': typeof AuthenticatedResumeReviewCheckoutRoute
  '/_authenticated/resume-review/return': typeof AuthenticatedResumeReviewReturnRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/resume-review/': typeof AuthenticatedResumeReviewIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/auth'
    | '/coaches'
    | '/contact'
    | '/directory'
    | '/employers'
    | '/membership'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/coach'
    | '/dashboard'
    | '/employer'
    | '/coaches/apply'
    | '/email/unsubscribe'
    | '/guide/international-relations-jobs-requirements'
    | '/admin/reviews'
    | '/admin/users'
    | '/coach/clients'
    | '/employer/resumes'
    | '/membership/checkout'
    | '/membership/return'
    | '/resume-review/checkout'
    | '/resume-review/return'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/coach/'
    | '/employer/'
    | '/resume-review/'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/auth'
    | '/coaches'
    | '/contact'
    | '/directory'
    | '/employers'
    | '/membership'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/dashboard'
    | '/coaches/apply'
    | '/email/unsubscribe'
    | '/guide/international-relations-jobs-requirements'
    | '/admin/reviews'
    | '/admin/users'
    | '/coach/clients'
    | '/employer/resumes'
    | '/membership/checkout'
    | '/membership/return'
    | '/resume-review/checkout'
    | '/resume-review/return'
    | '/lovable/email/suppression'
    | '/admin'
    | '/coach'
    | '/employer'
    | '/resume-review'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/auth'
    | '/coaches'
    | '/contact'
    | '/directory'
    | '/employers'
    | '/membership'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/employer'
    | '/coaches/apply'
    | '/email/unsubscribe'
    | '/guide/international-relations-jobs-requirements'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/users'
    | '/_authenticated/coach/clients'
    | '/_authenticated/employer/resumes'
    | '/_authenticated/membership/checkout'
    | '/_authenticated/membership/return'
    | '/_authenticated/resume-review/checkout'
    | '/_authenticated/resume-review/return'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/coach/'
    | '/_authenticated/employer/'
    | '/_authenticated/resume-review/'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  CoachesRoute: typeof CoachesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  EmployersRoute: typeof EmployersRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GuideInternationalRelationsJobsRequirementsRoute: typeof GuideInternationalRelationsJobsRequirementsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/international-relations-jobs-requirements': {
      id: '/guide/international-relations-jobs-requirements'
      path: '/guide/international-relations-jobs-requirements'
      fullPath: '/guide/international-relations-jobs-requirements'
      preLoaderRoute: typeof GuideInternationalRelationsJobsRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/apply': {
      id: '/coaches/apply'
      path: '/apply'
      fullPath: '/coaches/apply'
      preLoaderRoute: typeof CoachesApplyRouteImport
      parentRoute: typeof CoachesRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-review/': {
      id: '/_authenticated/resume-review/'
      path: '/resume-review'
      fullPath: '/resume-review/'
      preLoaderRoute: typeof AuthenticatedResumeReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume-review/return': {
      id: '/_authenticated/resume-review/return'
      path: '/resume-review/return'
      fullPath: '/resume-review/return'
      preLoaderRoute: typeof AuthenticatedResumeReviewReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-review/checkout': {
      id: '/_authenticated/resume-review/checkout'
      path: '/resume-review/checkout'
      fullPath: '/resume-review/checkout'
      preLoaderRoute: typeof AuthenticatedResumeReviewCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership/return': {
      id: '/_authenticated/membership/return'
      path: '/membership/return'
      fullPath: '/membership/return'
      preLoaderRoute: typeof AuthenticatedMembershipReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership/checkout': {
      id: '/_authenticated/membership/checkout'
      path: '/membership/checkout'
      fullPath: '/membership/checkout'
      preLoaderRoute: typeof AuthenticatedMembershipCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/resumes': {
      id: '/_authenticated/employer/resumes'
      path: '/resumes'
      fullPath: '/employer/resumes'
      preLoaderRoute: typeof AuthenticatedEmployerResumesRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/coach/clients': {
      id: '/_authenticated/coach/clients'
      path: '/clients'
      fullPath: '/coach/clients'
      preLoaderRoute: typeof AuthenticatedCoachClientsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachClientsRoute: typeof AuthenticatedCoachClientsRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachClientsRoute: AuthenticatedCoachClientsRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedEmployerRouteChildren {
  AuthenticatedEmployerResumesRoute: typeof AuthenticatedEmployerResumesRoute
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
}

const AuthenticatedEmployerRouteChildren: AuthenticatedEmployerRouteChildren = {
  AuthenticatedEmployerResumesRoute: AuthenticatedEmployerResumesRoute,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
}

const AuthenticatedEmployerRouteWithChildren =
  AuthenticatedEmployerRoute._addFileChildren(
    AuthenticatedEmployerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRouteWithChildren
  AuthenticatedMembershipCheckoutRoute: typeof AuthenticatedMembershipCheckoutRoute
  AuthenticatedMembershipReturnRoute: typeof AuthenticatedMembershipReturnRoute
  AuthenticatedResumeReviewCheckoutRoute: typeof AuthenticatedResumeReviewCheckoutRoute
  AuthenticatedResumeReviewReturnRoute: typeof AuthenticatedResumeReviewReturnRoute
  AuthenticatedResumeReviewIndexRoute: typeof AuthenticatedResumeReviewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRouteWithChildren,
  AuthenticatedMembershipCheckoutRoute: AuthenticatedMembershipCheckoutRoute,
  AuthenticatedMembershipReturnRoute: AuthenticatedMembershipReturnRoute,
  AuthenticatedResumeReviewCheckoutRoute:
    AuthenticatedResumeReviewCheckoutRoute,
  AuthenticatedResumeReviewReturnRoute: AuthenticatedResumeReviewReturnRoute,
  AuthenticatedResumeReviewIndexRoute: AuthenticatedResumeReviewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoachesRouteChildren {
  CoachesApplyRoute: typeof CoachesApplyRoute
}

const CoachesRouteChildren: CoachesRouteChildren = {
  CoachesApplyRoute: CoachesApplyRoute,
}

const CoachesRouteWithChildren =
  CoachesRoute._addFileChildren(CoachesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  CoachesRoute: CoachesRouteWithChildren,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  EmployersRoute: EmployersRoute,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GuideInternationalRelationsJobsRequirementsRoute:
    GuideInternationalRelationsJobsRequirementsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
