/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResumeDropRouteImport } from './routes/resume-drop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as BrandGuideRouteImport } from './routes/brand-guide'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachesIndexRouteImport } from './routes/coaches.index'
import { Route as GuideInternationalRelationsJobsRequirementsRouteImport } from './routes/guide.international-relations-jobs-requirements'
import { Route as EmployersSampleProfilesRouteImport } from './routes/employers.sample-profiles'
import { Route as EmployersResumeDropRouteImport } from './routes/employers.resume-drop'
import { Route as EmployersApplyRouteImport } from './routes/employers.apply'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CoachesApplyRouteImport } from './routes/coaches.apply'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedUniversityRouteImport } from './routes/_authenticated/university'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedResumeReviewIndexRouteImport } from './routes/_authenticated/resume-review.index'
import { Route as AuthenticatedResumeAnalysesIndexRouteImport } from './routes/_authenticated/resume-analyses.index'
import { Route as AuthenticatedEmployerIndexRouteImport } from './routes/_authenticated/employer.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicBootstrapPromosRouteImport } from './routes/api/public/bootstrap-promos'
import { Route as AuthenticatedResumeReviewReturnRouteImport } from './routes/_authenticated/resume-review.return'
import { Route as AuthenticatedResumeReviewCheckoutRouteImport } from './routes/_authenticated/resume-review.checkout'
import { Route as AuthenticatedResumeAnalysesAnalysisIdRouteImport } from './routes/_authenticated/resume-analyses.$analysisId'
import { Route as AuthenticatedMembershipReturnRouteImport } from './routes/_authenticated/membership.return'
import { Route as AuthenticatedMembershipCheckoutRouteImport } from './routes/_authenticated/membership.checkout'
import { Route as AuthenticatedEmployerUnlockedRouteImport } from './routes/_authenticated/employer.unlocked'
import { Route as AuthenticatedEmployerResumesRouteImport } from './routes/_authenticated/employer.resumes'
import { Route as AuthenticatedEmployerBrowseRouteImport } from './routes/_authenticated/employer.browse'
import { Route as AuthenticatedDashboardResumeStudioRouteImport } from './routes/_authenticated/dashboard.resume-studio'
import { Route as AuthenticatedDashboardResumeDropRouteImport } from './routes/_authenticated/dashboard.resume-drop'
import { Route as AuthenticatedDashboardOpportunitiesRouteImport } from './routes/_authenticated/dashboard.opportunities'
import { Route as AuthenticatedDashboardIntelRouteImport } from './routes/_authenticated/dashboard.intel'
import { Route as AuthenticatedDashboardCommunityRouteImport } from './routes/_authenticated/dashboard.community'
import { Route as AuthenticatedCoachClientsRouteImport } from './routes/_authenticated/coach.clients'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminUniversitiesRouteImport } from './routes/_authenticated/admin.universities'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin.organizations'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedDashboardCoachingIndexRouteImport } from './routes/_authenticated/dashboard.coaching.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedEmployerUnlockedCandidateIdRouteImport } from './routes/_authenticated/employer.unlocked.$candidateId'
import { Route as AuthenticatedEmployerCreditsReturnRouteImport } from './routes/_authenticated/employer.credits.return'
import { Route as AuthenticatedEmployerCreditsCheckoutRouteImport } from './routes/_authenticated/employer.credits.checkout'
import { Route as AuthenticatedDashboardCoachingCoachIdRouteImport } from './routes/_authenticated/dashboard.coaching.$coachId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeDropRoute = ResumeDropRouteImport.update({
  id: '/resume-drop',
  path: '/resume-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandGuideRoute = BrandGuideRouteImport.update({
  id: '/brand-guide',
  path: '/brand-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIndexRoute = CoachesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachesRoute,
} as any)
const GuideInternationalRelationsJobsRequirementsRoute =
  GuideInternationalRelationsJobsRequirementsRouteImport.update({
    id: '/guide/international-relations-jobs-requirements',
    path: '/guide/international-relations-jobs-requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployersSampleProfilesRoute = EmployersSampleProfilesRouteImport.update({
  id: '/sample-profiles',
  path: '/sample-profiles',
  getParentRoute: () => EmployersRoute,
} as any)
const EmployersResumeDropRoute = EmployersResumeDropRouteImport.update({
  id: '/resume-drop',
  path: '/resume-drop',
  getParentRoute: () => EmployersRoute,
} as any)
const EmployersApplyRoute = EmployersApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => EmployersRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesApplyRoute = CoachesApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CoachesRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUniversityRoute = AuthenticatedUniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResumeReviewIndexRoute =
  AuthenticatedResumeReviewIndexRouteImport.update({
    id: '/resume-review/',
    path: '/resume-review/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeAnalysesIndexRoute =
  AuthenticatedResumeAnalysesIndexRouteImport.update({
    id: '/resume-analyses/',
    path: '/resume-analyses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerIndexRoute =
  AuthenticatedEmployerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapPromosRoute =
  ApiPublicBootstrapPromosRouteImport.update({
    id: '/api/public/bootstrap-promos',
    path: '/api/public/bootstrap-promos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResumeReviewReturnRoute =
  AuthenticatedResumeReviewReturnRouteImport.update({
    id: '/resume-review/return',
    path: '/resume-review/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeReviewCheckoutRoute =
  AuthenticatedResumeReviewCheckoutRouteImport.update({
    id: '/resume-review/checkout',
    path: '/resume-review/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeAnalysesAnalysisIdRoute =
  AuthenticatedResumeAnalysesAnalysisIdRouteImport.update({
    id: '/resume-analyses/$analysisId',
    path: '/resume-analyses/$analysisId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembershipReturnRoute =
  AuthenticatedMembershipReturnRouteImport.update({
    id: '/membership/return',
    path: '/membership/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembershipCheckoutRoute =
  AuthenticatedMembershipCheckoutRouteImport.update({
    id: '/membership/checkout',
    path: '/membership/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerUnlockedRoute =
  AuthenticatedEmployerUnlockedRouteImport.update({
    id: '/unlocked',
    path: '/unlocked',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerResumesRoute =
  AuthenticatedEmployerResumesRouteImport.update({
    id: '/resumes',
    path: '/resumes',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerBrowseRoute =
  AuthenticatedEmployerBrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedDashboardResumeStudioRoute =
  AuthenticatedDashboardResumeStudioRouteImport.update({
    id: '/resume-studio',
    path: '/resume-studio',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardResumeDropRoute =
  AuthenticatedDashboardResumeDropRouteImport.update({
    id: '/resume-drop',
    path: '/resume-drop',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOpportunitiesRoute =
  AuthenticatedDashboardOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntelRoute =
  AuthenticatedDashboardIntelRouteImport.update({
    id: '/intel',
    path: '/intel',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCommunityRoute =
  AuthenticatedDashboardCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedCoachClientsRoute =
  AuthenticatedCoachClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUniversitiesRoute =
  AuthenticatedAdminUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardCoachingIndexRoute =
  AuthenticatedDashboardCoachingIndexRouteImport.update({
    id: '/coaching/',
    path: '/coaching/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEmployerUnlockedCandidateIdRoute =
  AuthenticatedEmployerUnlockedCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => AuthenticatedEmployerUnlockedRoute,
  } as any)
const AuthenticatedEmployerCreditsReturnRoute =
  AuthenticatedEmployerCreditsReturnRouteImport.update({
    id: '/credits/return',
    path: '/credits/return',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedEmployerCreditsCheckoutRoute =
  AuthenticatedEmployerCreditsCheckoutRouteImport.update({
    id: '/credits/checkout',
    path: '/credits/checkout',
    getParentRoute: () => AuthenticatedEmployerRoute,
  } as any)
const AuthenticatedDashboardCoachingCoachIdRoute =
  AuthenticatedDashboardCoachingCoachIdRouteImport.update({
    id: '/coaching/$coachId',
    path: '/coaching/$coachId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/brand-guide': typeof BrandGuideRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/employers': typeof EmployersRouteWithChildren
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume-drop': typeof ResumeDropRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/universities': typeof UniversitiesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/university': typeof AuthenticatedUniversityRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/coaches/apply': typeof CoachesApplyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/employers/apply': typeof EmployersApplyRoute
  '/employers/resume-drop': typeof EmployersResumeDropRoute
  '/employers/sample-profiles': typeof EmployersSampleProfilesRoute
  '/guide/international-relations-jobs-requirements': typeof GuideInternationalRelationsJobsRequirementsRoute
  '/coaches/': typeof CoachesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coach/clients': typeof AuthenticatedCoachClientsRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/intel': typeof AuthenticatedDashboardIntelRoute
  '/dashboard/opportunities': typeof AuthenticatedDashboardOpportunitiesRoute
  '/dashboard/resume-drop': typeof AuthenticatedDashboardResumeDropRoute
  '/dashboard/resume-studio': typeof AuthenticatedDashboardResumeStudioRoute
  '/employer/browse': typeof AuthenticatedEmployerBrowseRoute
  '/employer/resumes': typeof AuthenticatedEmployerResumesRoute
  '/employer/unlocked': typeof AuthenticatedEmployerUnlockedRouteWithChildren
  '/membership/checkout': typeof AuthenticatedMembershipCheckoutRoute
  '/membership/return': typeof AuthenticatedMembershipReturnRoute
  '/resume-analyses/$analysisId': typeof AuthenticatedResumeAnalysesAnalysisIdRoute
  '/resume-review/checkout': typeof AuthenticatedResumeReviewCheckoutRoute
  '/resume-review/return': typeof AuthenticatedResumeReviewReturnRoute
  '/api/public/bootstrap-promos': typeof ApiPublicBootstrapPromosRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/employer/': typeof AuthenticatedEmployerIndexRoute
  '/resume-analyses/': typeof AuthenticatedResumeAnalysesIndexRoute
  '/resume-review/': typeof AuthenticatedResumeReviewIndexRoute
  '/dashboard/coaching/$coachId': typeof AuthenticatedDashboardCoachingCoachIdRoute
  '/employer/credits/checkout': typeof AuthenticatedEmployerCreditsCheckoutRoute
  '/employer/credits/return': typeof AuthenticatedEmployerCreditsReturnRoute
  '/employer/unlocked/$candidateId': typeof AuthenticatedEmployerUnlockedCandidateIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/dashboard/coaching/': typeof AuthenticatedDashboardCoachingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/brand-guide': typeof BrandGuideRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/employers': typeof EmployersRouteWithChildren
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume-drop': typeof ResumeDropRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/universities': typeof UniversitiesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/university': typeof AuthenticatedUniversityRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/coaches/apply': typeof CoachesApplyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/employers/apply': typeof EmployersApplyRoute
  '/employers/resume-drop': typeof EmployersResumeDropRoute
  '/employers/sample-profiles': typeof EmployersSampleProfilesRoute
  '/guide/international-relations-jobs-requirements': typeof GuideInternationalRelationsJobsRequirementsRoute
  '/coaches': typeof CoachesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/coach/clients': typeof AuthenticatedCoachClientsRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/intel': typeof AuthenticatedDashboardIntelRoute
  '/dashboard/opportunities': typeof AuthenticatedDashboardOpportunitiesRoute
  '/dashboard/resume-drop': typeof AuthenticatedDashboardResumeDropRoute
  '/dashboard/resume-studio': typeof AuthenticatedDashboardResumeStudioRoute
  '/employer/browse': typeof AuthenticatedEmployerBrowseRoute
  '/employer/resumes': typeof AuthenticatedEmployerResumesRoute
  '/employer/unlocked': typeof AuthenticatedEmployerUnlockedRouteWithChildren
  '/membership/checkout': typeof AuthenticatedMembershipCheckoutRoute
  '/membership/return': typeof AuthenticatedMembershipReturnRoute
  '/resume-analyses/$analysisId': typeof AuthenticatedResumeAnalysesAnalysisIdRoute
  '/resume-review/checkout': typeof AuthenticatedResumeReviewCheckoutRoute
  '/resume-review/return': typeof AuthenticatedResumeReviewReturnRoute
  '/api/public/bootstrap-promos': typeof ApiPublicBootstrapPromosRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/employer': typeof AuthenticatedEmployerIndexRoute
  '/resume-analyses': typeof AuthenticatedResumeAnalysesIndexRoute
  '/resume-review': typeof AuthenticatedResumeReviewIndexRoute
  '/dashboard/coaching/$coachId': typeof AuthenticatedDashboardCoachingCoachIdRoute
  '/employer/credits/checkout': typeof AuthenticatedEmployerCreditsCheckoutRoute
  '/employer/credits/return': typeof AuthenticatedEmployerCreditsReturnRoute
  '/employer/unlocked/$candidateId': typeof AuthenticatedEmployerUnlockedCandidateIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/dashboard/coaching': typeof AuthenticatedDashboardCoachingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/brand-guide': typeof BrandGuideRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/employers': typeof EmployersRouteWithChildren
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resume-drop': typeof ResumeDropRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/universities': typeof UniversitiesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/employer': typeof AuthenticatedEmployerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/university': typeof AuthenticatedUniversityRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/coaches/apply': typeof CoachesApplyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/employers/apply': typeof EmployersApplyRoute
  '/employers/resume-drop': typeof EmployersResumeDropRoute
  '/employers/sample-profiles': typeof EmployersSampleProfilesRoute
  '/guide/international-relations-jobs-requirements': typeof GuideInternationalRelationsJobsRequirementsRoute
  '/coaches/': typeof CoachesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/universities': typeof AuthenticatedAdminUniversitiesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/coach/clients': typeof AuthenticatedCoachClientsRoute
  '/_authenticated/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/_authenticated/dashboard/intel': typeof AuthenticatedDashboardIntelRoute
  '/_authenticated/dashboard/opportunities': typeof AuthenticatedDashboardOpportunitiesRoute
  '/_authenticated/dashboard/resume-drop': typeof AuthenticatedDashboardResumeDropRoute
  '/_authenticated/dashboard/resume-studio': typeof AuthenticatedDashboardResumeStudioRoute
  '/_authenticated/employer/browse': typeof AuthenticatedEmployerBrowseRoute
  '/_authenticated/employer/resumes': typeof AuthenticatedEmployerResumesRoute
  '/_authenticated/employer/unlocked': typeof AuthenticatedEmployerUnlockedRouteWithChildren
  '/_authenticated/membership/checkout': typeof AuthenticatedMembershipCheckoutRoute
  '/_authenticated/membership/return': typeof AuthenticatedMembershipReturnRoute
  '/_authenticated/resume-analyses/$analysisId': typeof AuthenticatedResumeAnalysesAnalysisIdRoute
  '/_authenticated/resume-review/checkout': typeof AuthenticatedResumeReviewCheckoutRoute
  '/_authenticated/resume-review/return': typeof AuthenticatedResumeReviewReturnRoute
  '/api/public/bootstrap-promos': typeof ApiPublicBootstrapPromosRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/employer/': typeof AuthenticatedEmployerIndexRoute
  '/_authenticated/resume-analyses/': typeof AuthenticatedResumeAnalysesIndexRoute
  '/_authenticated/resume-review/': typeof AuthenticatedResumeReviewIndexRoute
  '/_authenticated/dashboard/coaching/$coachId': typeof AuthenticatedDashboardCoachingCoachIdRoute
  '/_authenticated/employer/credits/checkout': typeof AuthenticatedEmployerCreditsCheckoutRoute
  '/_authenticated/employer/credits/return': typeof AuthenticatedEmployerCreditsReturnRoute
  '/_authenticated/employer/unlocked/$candidateId': typeof AuthenticatedEmployerUnlockedCandidateIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/dashboard/coaching/': typeof AuthenticatedDashboardCoachingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/auth'
    | '/brand-guide'
    | '/coaches'
    | '/contact'
    | '/directory'
    | '/employers'
    | '/mcp'
    | '/membership'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/resume-drop'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/universities'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/billing'
    | '/coach'
    | '/dashboard'
    | '/employer'
    | '/profile'
    | '/university'
    | '/welcome'
    | '/coaches/apply'
    | '/email/unsubscribe'
    | '/employers/apply'
    | '/employers/resume-drop'
    | '/employers/sample-profiles'
    | '/guide/international-relations-jobs-requirements'
    | '/coaches/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/organizations'
    | '/admin/reviews'
    | '/admin/universities'
    | '/admin/users'
    | '/coach/clients'
    | '/dashboard/community'
    | '/dashboard/intel'
    | '/dashboard/opportunities'
    | '/dashboard/resume-drop'
    | '/dashboard/resume-studio'
    | '/employer/browse'
    | '/employer/resumes'
    | '/employer/unlocked'
    | '/membership/checkout'
    | '/membership/return'
    | '/resume-analyses/$analysisId'
    | '/resume-review/checkout'
    | '/resume-review/return'
    | '/api/public/bootstrap-promos'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/coach/'
    | '/dashboard/'
    | '/employer/'
    | '/resume-analyses/'
    | '/resume-review/'
    | '/dashboard/coaching/$coachId'
    | '/employer/credits/checkout'
    | '/employer/credits/return'
    | '/employer/unlocked/$candidateId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/dashboard/coaching/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/auth'
    | '/brand-guide'
    | '/contact'
    | '/directory'
    | '/employers'
    | '/mcp'
    | '/membership'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/resume-drop'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/universities'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing'
    | '/profile'
    | '/university'
    | '/welcome'
    | '/coaches/apply'
    | '/email/unsubscribe'
    | '/employers/apply'
    | '/employers/resume-drop'
    | '/employers/sample-profiles'
    | '/guide/international-relations-jobs-requirements'
    | '/coaches'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/organizations'
    | '/admin/reviews'
    | '/admin/universities'
    | '/admin/users'
    | '/coach/clients'
    | '/dashboard/community'
    | '/dashboard/intel'
    | '/dashboard/opportunities'
    | '/dashboard/resume-drop'
    | '/dashboard/resume-studio'
    | '/employer/browse'
    | '/employer/resumes'
    | '/employer/unlocked'
    | '/membership/checkout'
    | '/membership/return'
    | '/resume-analyses/$analysisId'
    | '/resume-review/checkout'
    | '/resume-review/return'
    | '/api/public/bootstrap-promos'
    | '/lovable/email/suppression'
    | '/admin'
    | '/coach'
    | '/dashboard'
    | '/employer'
    | '/resume-analyses'
    | '/resume-review'
    | '/dashboard/coaching/$coachId'
    | '/employer/credits/checkout'
    | '/employer/credits/return'
    | '/employer/unlocked/$candidateId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/dashboard/coaching'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/assessment'
    | '/auth'
    | '/brand-guide'
    | '/coaches'
    | '/contact'
    | '/directory'
    | '/employers'
    | '/mcp'
    | '/membership'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/resume-drop'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/universities'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/employer'
    | '/_authenticated/profile'
    | '/_authenticated/university'
    | '/_authenticated/welcome'
    | '/coaches/apply'
    | '/email/unsubscribe'
    | '/employers/apply'
    | '/employers/resume-drop'
    | '/employers/sample-profiles'
    | '/guide/international-relations-jobs-requirements'
    | '/coaches/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/universities'
    | '/_authenticated/admin/users'
    | '/_authenticated/coach/clients'
    | '/_authenticated/dashboard/community'
    | '/_authenticated/dashboard/intel'
    | '/_authenticated/dashboard/opportunities'
    | '/_authenticated/dashboard/resume-drop'
    | '/_authenticated/dashboard/resume-studio'
    | '/_authenticated/employer/browse'
    | '/_authenticated/employer/resumes'
    | '/_authenticated/employer/unlocked'
    | '/_authenticated/membership/checkout'
    | '/_authenticated/membership/return'
    | '/_authenticated/resume-analyses/$analysisId'
    | '/_authenticated/resume-review/checkout'
    | '/_authenticated/resume-review/return'
    | '/api/public/bootstrap-promos'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/coach/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/employer/'
    | '/_authenticated/resume-analyses/'
    | '/_authenticated/resume-review/'
    | '/_authenticated/dashboard/coaching/$coachId'
    | '/_authenticated/employer/credits/checkout'
    | '/_authenticated/employer/credits/return'
    | '/_authenticated/employer/unlocked/$candidateId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/dashboard/coaching/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  BrandGuideRoute: typeof BrandGuideRoute
  CoachesRoute: typeof CoachesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  EmployersRoute: typeof EmployersRouteWithChildren
  McpRoute: typeof McpRoute
  MembershipRoute: typeof MembershipRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResumeDropRoute: typeof ResumeDropRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UniversitiesRoute: typeof UniversitiesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GuideInternationalRelationsJobsRequirementsRoute: typeof GuideInternationalRelationsJobsRequirementsRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBootstrapPromosRoute: typeof ApiPublicBootstrapPromosRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-drop': {
      id: '/resume-drop'
      path: '/resume-drop'
      fullPath: '/resume-drop'
      preLoaderRoute: typeof ResumeDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-guide': {
      id: '/brand-guide'
      path: '/brand-guide'
      fullPath: '/brand-guide'
      preLoaderRoute: typeof BrandGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/': {
      id: '/coaches/'
      path: '/'
      fullPath: '/coaches/'
      preLoaderRoute: typeof CoachesIndexRouteImport
      parentRoute: typeof CoachesRoute
    }
    '/guide/international-relations-jobs-requirements': {
      id: '/guide/international-relations-jobs-requirements'
      path: '/guide/international-relations-jobs-requirements'
      fullPath: '/guide/international-relations-jobs-requirements'
      preLoaderRoute: typeof GuideInternationalRelationsJobsRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/sample-profiles': {
      id: '/employers/sample-profiles'
      path: '/sample-profiles'
      fullPath: '/employers/sample-profiles'
      preLoaderRoute: typeof EmployersSampleProfilesRouteImport
      parentRoute: typeof EmployersRoute
    }
    '/employers/resume-drop': {
      id: '/employers/resume-drop'
      path: '/resume-drop'
      fullPath: '/employers/resume-drop'
      preLoaderRoute: typeof EmployersResumeDropRouteImport
      parentRoute: typeof EmployersRoute
    }
    '/employers/apply': {
      id: '/employers/apply'
      path: '/apply'
      fullPath: '/employers/apply'
      preLoaderRoute: typeof EmployersApplyRouteImport
      parentRoute: typeof EmployersRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/apply': {
      id: '/coaches/apply'
      path: '/apply'
      fullPath: '/coaches/apply'
      preLoaderRoute: typeof CoachesApplyRouteImport
      parentRoute: typeof CoachesRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/university': {
      id: '/_authenticated/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof AuthenticatedUniversityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume-review/': {
      id: '/_authenticated/resume-review/'
      path: '/resume-review'
      fullPath: '/resume-review/'
      preLoaderRoute: typeof AuthenticatedResumeReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-analyses/': {
      id: '/_authenticated/resume-analyses/'
      path: '/resume-analyses'
      fullPath: '/resume-analyses/'
      preLoaderRoute: typeof AuthenticatedResumeAnalysesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/': {
      id: '/_authenticated/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AuthenticatedEmployerIndexRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-promos': {
      id: '/api/public/bootstrap-promos'
      path: '/api/public/bootstrap-promos'
      fullPath: '/api/public/bootstrap-promos'
      preLoaderRoute: typeof ApiPublicBootstrapPromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume-review/return': {
      id: '/_authenticated/resume-review/return'
      path: '/resume-review/return'
      fullPath: '/resume-review/return'
      preLoaderRoute: typeof AuthenticatedResumeReviewReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-review/checkout': {
      id: '/_authenticated/resume-review/checkout'
      path: '/resume-review/checkout'
      fullPath: '/resume-review/checkout'
      preLoaderRoute: typeof AuthenticatedResumeReviewCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-analyses/$analysisId': {
      id: '/_authenticated/resume-analyses/$analysisId'
      path: '/resume-analyses/$analysisId'
      fullPath: '/resume-analyses/$analysisId'
      preLoaderRoute: typeof AuthenticatedResumeAnalysesAnalysisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership/return': {
      id: '/_authenticated/membership/return'
      path: '/membership/return'
      fullPath: '/membership/return'
      preLoaderRoute: typeof AuthenticatedMembershipReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership/checkout': {
      id: '/_authenticated/membership/checkout'
      path: '/membership/checkout'
      fullPath: '/membership/checkout'
      preLoaderRoute: typeof AuthenticatedMembershipCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer/unlocked': {
      id: '/_authenticated/employer/unlocked'
      path: '/unlocked'
      fullPath: '/employer/unlocked'
      preLoaderRoute: typeof AuthenticatedEmployerUnlockedRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/resumes': {
      id: '/_authenticated/employer/resumes'
      path: '/resumes'
      fullPath: '/employer/resumes'
      preLoaderRoute: typeof AuthenticatedEmployerResumesRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/browse': {
      id: '/_authenticated/employer/browse'
      path: '/browse'
      fullPath: '/employer/browse'
      preLoaderRoute: typeof AuthenticatedEmployerBrowseRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/dashboard/resume-studio': {
      id: '/_authenticated/dashboard/resume-studio'
      path: '/resume-studio'
      fullPath: '/dashboard/resume-studio'
      preLoaderRoute: typeof AuthenticatedDashboardResumeStudioRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/resume-drop': {
      id: '/_authenticated/dashboard/resume-drop'
      path: '/resume-drop'
      fullPath: '/dashboard/resume-drop'
      preLoaderRoute: typeof AuthenticatedDashboardResumeDropRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/opportunities': {
      id: '/_authenticated/dashboard/opportunities'
      path: '/opportunities'
      fullPath: '/dashboard/opportunities'
      preLoaderRoute: typeof AuthenticatedDashboardOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/intel': {
      id: '/_authenticated/dashboard/intel'
      path: '/intel'
      fullPath: '/dashboard/intel'
      preLoaderRoute: typeof AuthenticatedDashboardIntelRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/community': {
      id: '/_authenticated/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof AuthenticatedDashboardCommunityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/coach/clients': {
      id: '/_authenticated/coach/clients'
      path: '/clients'
      fullPath: '/coach/clients'
      preLoaderRoute: typeof AuthenticatedCoachClientsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities': {
      id: '/_authenticated/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/coaching/': {
      id: '/_authenticated/dashboard/coaching/'
      path: '/coaching'
      fullPath: '/dashboard/coaching/'
      preLoaderRoute: typeof AuthenticatedDashboardCoachingIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/employer/unlocked/$candidateId': {
      id: '/_authenticated/employer/unlocked/$candidateId'
      path: '/$candidateId'
      fullPath: '/employer/unlocked/$candidateId'
      preLoaderRoute: typeof AuthenticatedEmployerUnlockedCandidateIdRouteImport
      parentRoute: typeof AuthenticatedEmployerUnlockedRoute
    }
    '/_authenticated/employer/credits/return': {
      id: '/_authenticated/employer/credits/return'
      path: '/credits/return'
      fullPath: '/employer/credits/return'
      preLoaderRoute: typeof AuthenticatedEmployerCreditsReturnRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/employer/credits/checkout': {
      id: '/_authenticated/employer/credits/checkout'
      path: '/credits/checkout'
      fullPath: '/employer/credits/checkout'
      preLoaderRoute: typeof AuthenticatedEmployerCreditsCheckoutRouteImport
      parentRoute: typeof AuthenticatedEmployerRoute
    }
    '/_authenticated/dashboard/coaching/$coachId': {
      id: '/_authenticated/dashboard/coaching/$coachId'
      path: '/coaching/$coachId'
      fullPath: '/dashboard/coaching/$coachId'
      preLoaderRoute: typeof AuthenticatedDashboardCoachingCoachIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminUniversitiesRoute: typeof AuthenticatedAdminUniversitiesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminUniversitiesRoute: AuthenticatedAdminUniversitiesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachClientsRoute: typeof AuthenticatedCoachClientsRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachClientsRoute: AuthenticatedCoachClientsRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCommunityRoute: typeof AuthenticatedDashboardCommunityRoute
  AuthenticatedDashboardIntelRoute: typeof AuthenticatedDashboardIntelRoute
  AuthenticatedDashboardOpportunitiesRoute: typeof AuthenticatedDashboardOpportunitiesRoute
  AuthenticatedDashboardResumeDropRoute: typeof AuthenticatedDashboardResumeDropRoute
  AuthenticatedDashboardResumeStudioRoute: typeof AuthenticatedDashboardResumeStudioRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCoachingCoachIdRoute: typeof AuthenticatedDashboardCoachingCoachIdRoute
  AuthenticatedDashboardCoachingIndexRoute: typeof AuthenticatedDashboardCoachingIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCommunityRoute: AuthenticatedDashboardCommunityRoute,
    AuthenticatedDashboardIntelRoute: AuthenticatedDashboardIntelRoute,
    AuthenticatedDashboardOpportunitiesRoute:
      AuthenticatedDashboardOpportunitiesRoute,
    AuthenticatedDashboardResumeDropRoute:
      AuthenticatedDashboardResumeDropRoute,
    AuthenticatedDashboardResumeStudioRoute:
      AuthenticatedDashboardResumeStudioRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCoachingCoachIdRoute:
      AuthenticatedDashboardCoachingCoachIdRoute,
    AuthenticatedDashboardCoachingIndexRoute:
      AuthenticatedDashboardCoachingIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedEmployerUnlockedRouteChildren {
  AuthenticatedEmployerUnlockedCandidateIdRoute: typeof AuthenticatedEmployerUnlockedCandidateIdRoute
}

const AuthenticatedEmployerUnlockedRouteChildren: AuthenticatedEmployerUnlockedRouteChildren =
  {
    AuthenticatedEmployerUnlockedCandidateIdRoute:
      AuthenticatedEmployerUnlockedCandidateIdRoute,
  }

const AuthenticatedEmployerUnlockedRouteWithChildren =
  AuthenticatedEmployerUnlockedRoute._addFileChildren(
    AuthenticatedEmployerUnlockedRouteChildren,
  )

interface AuthenticatedEmployerRouteChildren {
  AuthenticatedEmployerBrowseRoute: typeof AuthenticatedEmployerBrowseRoute
  AuthenticatedEmployerResumesRoute: typeof AuthenticatedEmployerResumesRoute
  AuthenticatedEmployerUnlockedRoute: typeof AuthenticatedEmployerUnlockedRouteWithChildren
  AuthenticatedEmployerIndexRoute: typeof AuthenticatedEmployerIndexRoute
  AuthenticatedEmployerCreditsCheckoutRoute: typeof AuthenticatedEmployerCreditsCheckoutRoute
  AuthenticatedEmployerCreditsReturnRoute: typeof AuthenticatedEmployerCreditsReturnRoute
}

const AuthenticatedEmployerRouteChildren: AuthenticatedEmployerRouteChildren = {
  AuthenticatedEmployerBrowseRoute: AuthenticatedEmployerBrowseRoute,
  AuthenticatedEmployerResumesRoute: AuthenticatedEmployerResumesRoute,
  AuthenticatedEmployerUnlockedRoute:
    AuthenticatedEmployerUnlockedRouteWithChildren,
  AuthenticatedEmployerIndexRoute: AuthenticatedEmployerIndexRoute,
  AuthenticatedEmployerCreditsCheckoutRoute:
    AuthenticatedEmployerCreditsCheckoutRoute,
  AuthenticatedEmployerCreditsReturnRoute:
    AuthenticatedEmployerCreditsReturnRoute,
}

const AuthenticatedEmployerRouteWithChildren =
  AuthenticatedEmployerRoute._addFileChildren(
    AuthenticatedEmployerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUniversityRoute: typeof AuthenticatedUniversityRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedMembershipCheckoutRoute: typeof AuthenticatedMembershipCheckoutRoute
  AuthenticatedMembershipReturnRoute: typeof AuthenticatedMembershipReturnRoute
  AuthenticatedResumeAnalysesAnalysisIdRoute: typeof AuthenticatedResumeAnalysesAnalysisIdRoute
  AuthenticatedResumeReviewCheckoutRoute: typeof AuthenticatedResumeReviewCheckoutRoute
  AuthenticatedResumeReviewReturnRoute: typeof AuthenticatedResumeReviewReturnRoute
  AuthenticatedResumeAnalysesIndexRoute: typeof AuthenticatedResumeAnalysesIndexRoute
  AuthenticatedResumeReviewIndexRoute: typeof AuthenticatedResumeReviewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUniversityRoute: AuthenticatedUniversityRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedMembershipCheckoutRoute: AuthenticatedMembershipCheckoutRoute,
  AuthenticatedMembershipReturnRoute: AuthenticatedMembershipReturnRoute,
  AuthenticatedResumeAnalysesAnalysisIdRoute:
    AuthenticatedResumeAnalysesAnalysisIdRoute,
  AuthenticatedResumeReviewCheckoutRoute:
    AuthenticatedResumeReviewCheckoutRoute,
  AuthenticatedResumeReviewReturnRoute: AuthenticatedResumeReviewReturnRoute,
  AuthenticatedResumeAnalysesIndexRoute: AuthenticatedResumeAnalysesIndexRoute,
  AuthenticatedResumeReviewIndexRoute: AuthenticatedResumeReviewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoachesRouteChildren {
  CoachesApplyRoute: typeof CoachesApplyRoute
  CoachesIndexRoute: typeof CoachesIndexRoute
}

const CoachesRouteChildren: CoachesRouteChildren = {
  CoachesApplyRoute: CoachesApplyRoute,
  CoachesIndexRoute: CoachesIndexRoute,
}

const CoachesRouteWithChildren =
  CoachesRoute._addFileChildren(CoachesRouteChildren)

interface EmployersRouteChildren {
  EmployersApplyRoute: typeof EmployersApplyRoute
  EmployersResumeDropRoute: typeof EmployersResumeDropRoute
  EmployersSampleProfilesRoute: typeof EmployersSampleProfilesRoute
}

const EmployersRouteChildren: EmployersRouteChildren = {
  EmployersApplyRoute: EmployersApplyRoute,
  EmployersResumeDropRoute: EmployersResumeDropRoute,
  EmployersSampleProfilesRoute: EmployersSampleProfilesRoute,
}

const EmployersRouteWithChildren = EmployersRoute._addFileChildren(
  EmployersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  BrandGuideRoute: BrandGuideRoute,
  CoachesRoute: CoachesRouteWithChildren,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  EmployersRoute: EmployersRouteWithChildren,
  McpRoute: McpRoute,
  MembershipRoute: MembershipRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResumeDropRoute: ResumeDropRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UniversitiesRoute: UniversitiesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GuideInternationalRelationsJobsRequirementsRoute:
    GuideInternationalRelationsJobsRequirementsRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBootstrapPromosRoute: ApiPublicBootstrapPromosRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
