ALTER TABLE public.coach_applications
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS location text,
  ADD COLUMN IF NOT EXISTS timezone text,
  ADD COLUMN IF NOT EXISTS clients_capacity integer,
  ADD COLUMN IF NOT EXISTS hours_per_week integer,
  ADD COLUMN IF NOT EXISTS availability text,
  ADD COLUMN IF NOT EXISTS preferred_client_levels text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS languages text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS education text,
  ADD COLUMN IF NOT EXISTS notable_experience text,
  ADD COLUMN IF NOT EXISTS coaching_experience text,
  ADD COLUMN IF NOT EXISTS approach text,
  ADD COLUMN IF NOT EXISTS start_date text,
  ADD COLUMN IF NOT EXISTS referral_source text,
  ADD COLUMN IF NOT EXISTS compensation_expectations text,
  ADD COLUMN IF NOT EXISTS conflicts_disclosure text,
  ADD COLUMN IF NOT EXISTS agree_background_check boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS agree_terms boolean NOT NULL DEFAULT false;